callbacks = ["ProgressCallback"]
funcs = []
namespace = "Flatpak"
version = "1.0"

[[types]]
  err_funcs = ["flatpak_installation_install_full","flatpak_installation_list_installed_refs","flatpak_installation_list_installed_refs_by_kind","flatpak_installation_list_installed_refs_for_update","flatpak_installation_list_installed_related_refs_sync","flatpak_installation_list_remote_refs_sync","flatpak_installation_list_remote_related_refs_sync","flatpak_installation_list_remotes","flatpak_installation_update_appstream_full_sync","flatpak_installation_update_appstream_sync","flatpak_installation_update_full"]
  funcs = ["flatpak_installation_new_for_path","flatpak_installation_new_system","flatpak_installation_new_system_with_id","flatpak_installation_new_user","flatpak_installation_create_monitor","flatpak_installation_drop_caches","flatpak_installation_fetch_remote_metadata_sync","flatpak_installation_fetch_remote_ref_sync","flatpak_installation_fetch_remote_size_sync","flatpak_installation_get_current_installed_app","flatpak_installation_get_display_name","flatpak_installation_get_id","flatpak_installation_get_installed_ref","flatpak_installation_get_is_user","flatpak_installation_get_path","flatpak_installation_get_priority","flatpak_installation_get_remote_by_name","flatpak_installation_get_storage_type","flatpak_installation_install_ref_file","flatpak_installation_launch","flatpak_installation_load_app_overrides","flatpak_installation_modify_remote","flatpak_installation_remove_remote","flatpak_installation_update_remote_sync","flatpak_installation_install","flatpak_installation_install_bundle","flatpak_installation_uninstall","flatpak_installation_update"]
  ignore_funcs = []
  manual_funcs = []
  name = "Installation"

[[types]]
  err_funcs = []
  funcs = ["flatpak_ref_format_ref","flatpak_ref_get_arch","flatpak_ref_get_branch","flatpak_ref_get_commit","flatpak_ref_get_kind","flatpak_ref_get_name","flatpak_ref_parse"]
  ignore_funcs = []
  manual_funcs = []
  name = "Ref"

[[types]]
  err_funcs = ["flatpak_installed_ref_get_subpaths"]
  funcs = ["flatpak_installed_ref_get_deploy_dir","flatpak_installed_ref_get_installed_size","flatpak_installed_ref_get_is_current","flatpak_installed_ref_get_latest_commit","flatpak_installed_ref_get_origin","flatpak_installed_ref_load_metadata"]
  ignore_funcs = []
  manual_funcs = []
  name = "InstalledRef"

[[types]]
  err_funcs = []
  funcs = ["flatpak_remote_ref_get_remote_name"]
  ignore_funcs = []
  manual_funcs = []
  name = "RemoteRef"

[[types]]
  err_funcs = []
  funcs = ["flatpak_bundle_ref_new","flatpak_bundle_ref_get_appstream","flatpak_bundle_ref_get_file","flatpak_bundle_ref_get_icon","flatpak_bundle_ref_get_installed_size","flatpak_bundle_ref_get_metadata","flatpak_bundle_ref_get_origin","flatpak_bundle_ref_get_runtime_repo_url"]
  ignore_funcs = []
  manual_funcs = []
  name = "BundleRef"

[[types]]
  err_funcs = []
  funcs = ["flatpak_remote_new","flatpak_remote_get_appstream_dir","flatpak_remote_get_appstream_timestamp","flatpak_remote_get_default_branch","flatpak_remote_get_disabled","flatpak_remote_get_gpg_verify","flatpak_remote_get_name","flatpak_remote_get_nodeps","flatpak_remote_get_noenumerate","flatpak_remote_get_prio","flatpak_remote_get_title","flatpak_remote_get_url","flatpak_remote_set_default_branch","flatpak_remote_set_disabled","flatpak_remote_set_gpg_key","flatpak_remote_set_gpg_verify","flatpak_remote_set_nodeps","flatpak_remote_set_noenumerate","flatpak_remote_set_prio","flatpak_remote_set_title","flatpak_remote_set_url"]
  ignore_funcs = []
  manual_funcs = []
  name = "Remote"
