callbacks = []
funcs = []
ignore_types = []
namespace = "cairo"
version = "1.0"
cincludes = ["<cairo-gobject.h>"]

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "Context"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "Surface"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "Matrix"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "Pattern"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "Region"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "FontOptions"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "FontType"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "FontFace"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "ScaledFont"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "Path"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "RectangleInt"
