callbacks = []
cincludes = []
funcs = []
ignore_types = []
namespace = "Gdk"
version = "3.0"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = ["gdk_color_copy","gdk_color_equal","gdk_color_free","gdk_color_hash","gdk_color_to_string","gdk_color_parse"]
  manual_funcs = []
  name = "Color"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventAny"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventButton"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventConfigure"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventCrossing"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventDND"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventExpose"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventFocus"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventGrabBroken"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventKey"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventMotion"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventOwnerChange"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventPadAxis"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventPadButton"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventPadGroupMode"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventProperty"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventProximity"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventScroll"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventSelection"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventSequence"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventSetting"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventTouch"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventTouchpadPinch"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventTouchpadSwipe"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventVisibility"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "EventWindowState"

[[types]]
  err_funcs = []
  funcs = ["gdk_frame_timings_get_complete","gdk_frame_timings_get_frame_counter","gdk_frame_timings_get_frame_time","gdk_frame_timings_get_predicted_presentation_time","gdk_frame_timings_get_presentation_time","gdk_frame_timings_get_refresh_interval","gdk_frame_timings_ref","gdk_frame_timings_unref"]
  ignore_funcs = []
  manual_funcs = []
  name = "FrameTimings"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "Geometry"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "KeymapKey"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "Point"

[[types]]
  err_funcs = []
  funcs = ["gdk_rgba_copy","gdk_rgba_equal","gdk_rgba_free","gdk_rgba_hash","gdk_rgba_parse","gdk_rgba_to_string"]
  ignore_funcs = []
  manual_funcs = []
  name = "RGBA"

[[types]]
  err_funcs = []
  funcs = ["gdk_rectangle_equal","gdk_rectangle_intersect","gdk_rectangle_union"]
  ignore_funcs = []
  manual_funcs = []
  name = "Rectangle"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "TimeCoord"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "WindowAttr"

[[types]]
  err_funcs = []
  funcs = ["gdk_device_pad_get_feature_group","gdk_device_pad_get_group_n_modes","gdk_device_pad_get_n_features","gdk_device_pad_get_n_groups"]
  ignore_funcs = []
  manual_funcs = []
  name = "DevicePad"

[[types]]
  err_funcs = []
  funcs = ["gdk_app_launch_context_set_desktop","gdk_app_launch_context_set_icon","gdk_app_launch_context_set_icon_name","gdk_app_launch_context_set_screen","gdk_app_launch_context_set_timestamp"]
  ignore_funcs = ["gdk_app_launch_context_new","gdk_app_launch_context_set_display"]
  manual_funcs = []
  name = "AppLaunchContext"

[[types]]
  err_funcs = []
  funcs = ["gdk_screen_get_display","gdk_screen_get_font_options","gdk_screen_get_resolution","gdk_screen_get_rgba_visual","gdk_screen_get_root_window","gdk_screen_get_setting","gdk_screen_get_system_visual","gdk_screen_get_toplevel_windows","gdk_screen_get_window_stack","gdk_screen_is_composited","gdk_screen_list_visuals","gdk_screen_set_font_options","gdk_screen_set_resolution","gdk_screen_get_default"]
  ignore_funcs = ["gdk_screen_get_active_window","gdk_screen_get_height","gdk_screen_get_height_mm","gdk_screen_get_monitor_at_point","gdk_screen_get_monitor_at_window","gdk_screen_get_monitor_geometry","gdk_screen_get_monitor_height_mm","gdk_screen_get_monitor_plug_name","gdk_screen_get_monitor_scale_factor","gdk_screen_get_monitor_width_mm","gdk_screen_get_monitor_workarea","gdk_screen_get_n_monitors","gdk_screen_get_number","gdk_screen_get_primary_monitor","gdk_screen_get_width","gdk_screen_get_width_mm","gdk_screen_make_display_name","gdk_screen_height","gdk_screen_height_mm","gdk_screen_width","gdk_screen_width_mm"]
  manual_funcs = []
  name = "Screen"

[[types]]
  err_funcs = ["gdk_display_get_event","gdk_display_peek_event","gdk_display_put_event","gdk_display_request_selection_notification","gdk_display_store_clipboard"]
  funcs = ["gdk_display_beep","gdk_display_close","gdk_display_device_is_grabbed","gdk_display_flush","gdk_display_get_app_launch_context","gdk_display_get_default_cursor_size","gdk_display_get_default_group","gdk_display_get_default_screen","gdk_display_get_default_seat","gdk_display_get_maximal_cursor_size","gdk_display_get_monitor","gdk_display_get_monitor_at_point","gdk_display_get_monitor_at_window","gdk_display_get_n_monitors","gdk_display_get_name","gdk_display_get_primary_monitor","gdk_display_has_pending","gdk_display_is_closed","gdk_display_list_seats","gdk_display_notify_startup_complete","gdk_display_set_double_click_distance","gdk_display_set_double_click_time","gdk_display_supports_clipboard_persistence","gdk_display_supports_cursor_alpha","gdk_display_supports_cursor_color","gdk_display_supports_input_shapes","gdk_display_supports_selection_notification","gdk_display_supports_shapes","gdk_display_sync","gdk_display_get_default","gdk_display_open"]
  ignore_funcs = ["gdk_display_get_device_manager","gdk_display_get_n_screens","gdk_display_get_pointer","gdk_display_get_screen","gdk_display_get_window_at_pointer","gdk_display_keyboard_ungrab","gdk_display_list_devices","gdk_display_pointer_is_grabbed","gdk_display_pointer_ungrab","gdk_display_supports_composite","gdk_display_warp_pointer","gdk_display_open_default_libgtk_only"]
  manual_funcs = []
  name = "Display"

[[types]]
  err_funcs = ["gdk_device_get_axis_value","gdk_device_get_history"]
  funcs = ["gdk_device_get_associated_device","gdk_device_get_axes","gdk_device_get_axis","gdk_device_get_axis_use","gdk_device_get_device_type","gdk_device_get_display","gdk_device_get_has_cursor","gdk_device_get_key","gdk_device_get_last_event_window","gdk_device_get_mode","gdk_device_get_n_axes","gdk_device_get_n_keys","gdk_device_get_name","gdk_device_get_position","gdk_device_get_position_double","gdk_device_get_product_id","gdk_device_get_seat","gdk_device_get_source","gdk_device_get_state","gdk_device_get_vendor_id","gdk_device_get_window_at_position","gdk_device_get_window_at_position_double","gdk_device_list_axes","gdk_device_list_slave_devices","gdk_device_set_axis_use","gdk_device_set_key","gdk_device_set_mode","gdk_device_warp","gdk_device_free_history"]
  ignore_funcs = ["gdk_device_grab","gdk_device_ungrab","gdk_device_grab_info_libgtk_only"]
  manual_funcs = []
  name = "Device"

[[types]]
  err_funcs = ["gdk_window_new","gdk_window_add_filter","gdk_window_create_similar_image_surface","gdk_window_destroy_notify","gdk_window_invalidate_maybe_recurse","gdk_window_remove_filter","gdk_window_set_invalidate_handler","gdk_window_show_window_menu"]
  funcs = ["gdk_window_beep","gdk_window_begin_move_drag","gdk_window_begin_move_drag_for_device","gdk_window_begin_resize_drag","gdk_window_begin_resize_drag_for_device","gdk_window_coords_from_parent","gdk_window_coords_to_parent","gdk_window_create_gl_context","gdk_window_create_similar_surface","gdk_window_deiconify","gdk_window_destroy","gdk_window_end_draw_frame","gdk_window_ensure_native","gdk_window_focus","gdk_window_freeze_updates","gdk_window_fullscreen","gdk_window_fullscreen_on_monitor","gdk_window_geometry_changed","gdk_window_get_accept_focus","gdk_window_get_children","gdk_window_get_children_with_user_data","gdk_window_get_clip_region","gdk_window_get_cursor","gdk_window_get_decorations","gdk_window_get_device_cursor","gdk_window_get_device_events","gdk_window_get_device_position","gdk_window_get_device_position_double","gdk_window_get_display","gdk_window_get_drag_protocol","gdk_window_get_effective_parent","gdk_window_get_effective_toplevel","gdk_window_get_event_compression","gdk_window_get_events","gdk_window_get_focus_on_map","gdk_window_get_frame_clock","gdk_window_get_fullscreen_mode","gdk_window_get_geometry","gdk_window_get_group","gdk_window_get_height","gdk_window_get_modal_hint","gdk_window_get_origin","gdk_window_get_parent","gdk_window_get_pass_through","gdk_window_get_position","gdk_window_get_root_coords","gdk_window_get_root_origin","gdk_window_get_scale_factor","gdk_window_get_screen","gdk_window_get_source_events","gdk_window_get_state","gdk_window_get_support_multidevice","gdk_window_get_toplevel","gdk_window_get_type_hint","gdk_window_get_update_area","gdk_window_get_user_data","gdk_window_get_visible_region","gdk_window_get_visual","gdk_window_get_width","gdk_window_get_window_type","gdk_window_has_native","gdk_window_hide","gdk_window_iconify","gdk_window_input_shape_combine_region","gdk_window_invalidate_rect","gdk_window_invalidate_region","gdk_window_is_destroyed","gdk_window_is_input_only","gdk_window_is_shaped","gdk_window_is_viewable","gdk_window_is_visible","gdk_window_lower","gdk_window_mark_paint_from_clip","gdk_window_maximize","gdk_window_merge_child_input_shapes","gdk_window_merge_child_shapes","gdk_window_move","gdk_window_move_region","gdk_window_move_resize","gdk_window_peek_children","gdk_window_raise","gdk_window_register_dnd","gdk_window_reparent","gdk_window_resize","gdk_window_restack","gdk_window_scroll","gdk_window_set_accept_focus","gdk_window_set_child_input_shapes","gdk_window_set_child_shapes","gdk_window_set_cursor","gdk_window_set_decorations","gdk_window_set_device_cursor","gdk_window_set_device_events","gdk_window_set_event_compression","gdk_window_set_events","gdk_window_set_focus_on_map","gdk_window_set_fullscreen_mode","gdk_window_set_functions","gdk_window_set_geometry_hints","gdk_window_set_group","gdk_window_set_icon_list","gdk_window_set_icon_name","gdk_window_set_keep_above","gdk_window_set_keep_below","gdk_window_set_modal_hint","gdk_window_set_opacity","gdk_window_set_opaque_region","gdk_window_set_override_redirect","gdk_window_set_pass_through","gdk_window_set_role","gdk_window_set_shadow_width","gdk_window_set_skip_pager_hint","gdk_window_set_skip_taskbar_hint","gdk_window_set_source_events","gdk_window_set_startup_id","gdk_window_set_support_multidevice","gdk_window_set_title","gdk_window_set_transient_for","gdk_window_set_type_hint","gdk_window_set_urgency_hint","gdk_window_set_user_data","gdk_window_shape_combine_region","gdk_window_show","gdk_window_show_unraised","gdk_window_stick","gdk_window_thaw_updates","gdk_window_unfullscreen","gdk_window_unmaximize","gdk_window_unstick","gdk_window_withdraw","gdk_window_constrain_size","gdk_window_get_frame_extents","gdk_window_begin_draw_frame"]
  ignore_funcs = ["gdk_window_begin_paint_rect","gdk_window_begin_paint_region","gdk_window_configure_finished","gdk_window_enable_synchronized_configure","gdk_window_flush","gdk_window_freeze_toplevel_updates_libgtk_only","gdk_window_get_background_pattern","gdk_window_get_composited","gdk_window_end_paint","gdk_window_get_pointer","gdk_window_process_updates","gdk_window_set_background","gdk_window_set_background_pattern","gdk_window_set_background_rgba","gdk_window_set_composited","gdk_window_set_static_gravities","gdk_window_thaw_toplevel_updates_libgtk_only","gdk_window_at_pointer","gdk_window_process_all_updates","gdk_window_set_debug_updates"]
  manual_funcs = []
  name = "Window"

[[types]]
  err_funcs = []
  funcs = ["gdk_gl_context_get_debug_enabled","gdk_gl_context_get_display","gdk_gl_context_get_forward_compatible","gdk_gl_context_get_required_version","gdk_gl_context_get_shared_context","gdk_gl_context_get_use_es","gdk_gl_context_get_version","gdk_gl_context_get_window","gdk_gl_context_is_legacy","gdk_gl_context_make_current","gdk_gl_context_realize","gdk_gl_context_set_debug_enabled","gdk_gl_context_set_forward_compatible","gdk_gl_context_set_required_version","gdk_gl_context_set_use_es","gdk_gl_context_clear_current","gdk_gl_context_get_current"]
  ignore_funcs = []
  manual_funcs = []
  name = "GLContext"

[[types]]
  err_funcs = []
  funcs = ["gdk_drawing_context_get_cairo_context","gdk_drawing_context_get_clip","gdk_drawing_context_get_window","gdk_drawing_context_is_valid"]
  ignore_funcs = []
  manual_funcs = []
  name = "DrawingContext"

[[types]]
  err_funcs = []
  funcs = ["gdk_cursor_new_for_display","gdk_cursor_new_from_name","gdk_cursor_new_from_surface","gdk_cursor_get_cursor_type","gdk_cursor_get_display","gdk_cursor_get_image","gdk_cursor_get_surface","gdk_cursor_new_from_pixbuf"]
  ignore_funcs = ["gdk_cursor_new","gdk_cursor_ref","gdk_cursor_unref"]
  manual_funcs = []
  name = "Cursor"

[[types]]
  err_funcs = ["gdk_seat_grab"]
  funcs = ["gdk_seat_get_capabilities","gdk_seat_get_display","gdk_seat_get_keyboard","gdk_seat_get_pointer","gdk_seat_get_slaves","gdk_seat_ungrab"]
  ignore_funcs = []
  manual_funcs = []
  name = "Seat"

[[types]]
  err_funcs = ["gdk_atom_name"]
  funcs = ["gdk_atom_intern","gdk_atom_intern_static_string"]
  ignore_funcs = []
  manual_funcs = []
  name = "Atom"

[[types]]
  err_funcs = []
  funcs = ["gdk_device_manager_get_display"]
  ignore_funcs = ["gdk_device_manager_get_client_pointer","gdk_device_manager_list_devices"]
  manual_funcs = []
  name = "DeviceManager"

[[types]]
  err_funcs = []
  funcs = ["gdk_device_tool_get_hardware_id","gdk_device_tool_get_serial","gdk_device_tool_get_tool_type"]
  ignore_funcs = []
  manual_funcs = []
  name = "DeviceTool"

[[types]]
  err_funcs = []
  funcs = ["gdk_monitor_get_display","gdk_monitor_get_height_mm","gdk_monitor_get_manufacturer","gdk_monitor_get_model","gdk_monitor_get_refresh_rate","gdk_monitor_get_scale_factor","gdk_monitor_get_subpixel_layout","gdk_monitor_get_width_mm","gdk_monitor_is_primary","gdk_monitor_get_geometry","gdk_monitor_get_workarea"]
  ignore_funcs = []
  manual_funcs = []
  name = "Monitor"

[[types]]
  err_funcs = []
  funcs = ["gdk_display_manager_get_default_display","gdk_display_manager_open_display","gdk_display_manager_set_default_display","gdk_display_manager_get","gdk_display_manager_list_displays"]
  ignore_funcs = []
  manual_funcs = []
  name = "DisplayManager"

[[types]]
  err_funcs = []
  funcs = ["gdk_drag_context_get_actions","gdk_drag_context_get_dest_window","gdk_drag_context_get_device","gdk_drag_context_get_drag_window","gdk_drag_context_get_protocol","gdk_drag_context_get_selected_action","gdk_drag_context_get_source_window","gdk_drag_context_get_suggested_action","gdk_drag_context_list_targets","gdk_drag_context_manage_dnd","gdk_drag_context_set_device","gdk_drag_context_set_hotspot"]
  ignore_funcs = []
  manual_funcs = []
  name = "DragContext"

[[types]]
  err_funcs = ["gdk_frame_clock_get_refresh_info"]
  funcs = ["gdk_frame_clock_begin_updating","gdk_frame_clock_end_updating","gdk_frame_clock_get_current_timings","gdk_frame_clock_get_frame_counter","gdk_frame_clock_get_frame_time","gdk_frame_clock_get_history_start","gdk_frame_clock_get_timings","gdk_frame_clock_request_phase"]
  ignore_funcs = []
  manual_funcs = []
  name = "FrameClock"

[[types]]
  err_funcs = ["gdk_keymap_add_virtual_modifiers","gdk_keymap_get_entries_for_keycode","gdk_keymap_get_entries_for_keyval","gdk_keymap_map_virtual_modifiers"]
  funcs = ["gdk_keymap_get_caps_lock_state","gdk_keymap_get_direction","gdk_keymap_get_modifier_mask","gdk_keymap_get_modifier_state","gdk_keymap_get_num_lock_state","gdk_keymap_get_scroll_lock_state","gdk_keymap_have_bidi_layouts","gdk_keymap_lookup_key","gdk_keymap_translate_keyboard_state","gdk_keymap_get_default","gdk_keymap_get_for_display"]
  ignore_funcs = []
  manual_funcs = []
  name = "Keymap"

[[types]]
  err_funcs = []
  funcs = ["gdk_visual_get_blue_pixel_details","gdk_visual_get_depth","gdk_visual_get_green_pixel_details","gdk_visual_get_red_pixel_details","gdk_visual_get_screen","gdk_visual_get_visual_type"]
  ignore_funcs = ["gdk_visual_get_bits_per_rgb","gdk_visual_get_byte_order","gdk_visual_get_colormap_size","gdk_visual_get_best","gdk_visual_get_best_depth","gdk_visual_get_best_type","gdk_visual_get_best_with_both","gdk_visual_get_best_with_depth","gdk_visual_get_best_with_type","gdk_visual_get_system"]
  manual_funcs = []
  name = "Visual"
