callbacks = []
funcs = []
ignore_types = ["LayoutRun","Engine","EngineInfo","EngineScriptInfo","IncludedModule","ScriptForLang","EngineLang","EngineShape","FontsetSimple"]
namespace = "Pango"
version = "1.0"

[[types]]
  err_funcs = ["pango_glyph_item_apply_attrs","pango_glyph_item_letter_space"]
  funcs = ["pango_glyph_item_copy","pango_glyph_item_free","pango_glyph_item_get_logical_widths","pango_glyph_item_split"]
  ignore_funcs = []
  manual_funcs = []
  name = "GlyphItem"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "Analysis"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "AttrClass"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "AttrColor"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "AttrFloat"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "AttrInt"

[[types]]
  err_funcs = ["pango_attr_list_filter"]
  funcs = ["pango_attr_list_new","pango_attr_list_change","pango_attr_list_copy","pango_attr_list_get_iterator","pango_attr_list_insert","pango_attr_list_insert_before","pango_attr_list_ref","pango_attr_list_splice","pango_attr_list_unref"]
  ignore_funcs = []
  manual_funcs = []
  name = "AttrList"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "AttrString"

[[types]]
  err_funcs = []
  funcs = ["pango_attribute_copy","pango_attribute_destroy","pango_attribute_equal","pango_attribute_init"]
  ignore_funcs = []
  manual_funcs = []
  name = "Attribute"

[[types]]
  err_funcs = []
  funcs = ["pango_color_copy","pango_color_free","pango_color_parse","pango_color_to_string"]
  ignore_funcs = []
  manual_funcs = []
  name = "Color"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "GlyphGeometry"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "GlyphInfo"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "GlyphVisAttr"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "LogAttr"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "Rectangle"

[[types]]
  err_funcs = []
  funcs = ["pango_attr_font_desc_new"]
  ignore_funcs = []
  manual_funcs = []
  name = "AttrFontDesc"

[[types]]
  err_funcs = []
  funcs = ["pango_font_description_new","pango_font_description_better_match","pango_font_description_copy","pango_font_description_copy_static","pango_font_description_equal","pango_font_description_free","pango_font_description_get_family","pango_font_description_get_gravity","pango_font_description_get_set_fields","pango_font_description_get_size","pango_font_description_get_size_is_absolute","pango_font_description_get_stretch","pango_font_description_get_style","pango_font_description_get_variant","pango_font_description_get_weight","pango_font_description_hash","pango_font_description_merge","pango_font_description_merge_static","pango_font_description_set_absolute_size","pango_font_description_set_family","pango_font_description_set_family_static","pango_font_description_set_gravity","pango_font_description_set_size","pango_font_description_set_stretch","pango_font_description_set_style","pango_font_description_set_variant","pango_font_description_set_weight","pango_font_description_to_filename","pango_font_description_to_string","pango_font_description_unset_fields","pango_font_description_from_string"]
  ignore_funcs = []
  manual_funcs = []
  name = "FontDescription"

[[types]]
  err_funcs = []
  funcs = ["pango_attr_font_features_new"]
  ignore_funcs = []
  manual_funcs = []
  name = "AttrFontFeatures"

[[types]]
  err_funcs = []
  funcs = ["pango_attr_language_new"]
  ignore_funcs = []
  manual_funcs = []
  name = "AttrLanguage"

[[types]]
  err_funcs = []
  funcs = ["pango_language_get_sample_string","pango_language_get_scripts","pango_language_includes_script","pango_language_matches","pango_language_to_string","pango_language_from_string","pango_language_get_default"]
  ignore_funcs = []
  manual_funcs = []
  name = "Language"

[[types]]
  err_funcs = ["pango_attr_iterator_get_attrs","pango_attr_iterator_get_font"]
  funcs = ["pango_attr_iterator_copy","pango_attr_iterator_destroy","pango_attr_iterator_get","pango_attr_iterator_next","pango_attr_iterator_range"]
  ignore_funcs = []
  manual_funcs = []
  name = "AttrIterator"

[[types]]
  err_funcs = ["pango_attr_shape_new_with_data"]
  funcs = ["pango_attr_shape_new"]
  ignore_funcs = []
  manual_funcs = []
  name = "AttrShape"

[[types]]
  err_funcs = []
  funcs = ["pango_attr_size_new","pango_attr_size_new_absolute"]
  ignore_funcs = []
  manual_funcs = []
  name = "AttrSize"

[[types]]
  err_funcs = []
  funcs = ["pango_font_metrics_get_approximate_char_width","pango_font_metrics_get_approximate_digit_width","pango_font_metrics_get_ascent","pango_font_metrics_get_descent","pango_font_metrics_get_strikethrough_position","pango_font_metrics_get_strikethrough_thickness","pango_font_metrics_get_underline_position","pango_font_metrics_get_underline_thickness","pango_font_metrics_ref","pango_font_metrics_unref"]
  ignore_funcs = ["pango_font_metrics_new"]
  manual_funcs = []
  name = "FontMetrics"

[[types]]
  err_funcs = []
  funcs = ["pango_glyph_item_iter_copy","pango_glyph_item_iter_free","pango_glyph_item_iter_init_end","pango_glyph_item_iter_init_start","pango_glyph_item_iter_next_cluster","pango_glyph_item_iter_prev_cluster"]
  ignore_funcs = []
  manual_funcs = []
  name = "GlyphItemIter"

[[types]]
  err_funcs = ["pango_glyph_string_extents","pango_glyph_string_extents_range"]
  funcs = ["pango_glyph_string_new","pango_glyph_string_copy","pango_glyph_string_free","pango_glyph_string_get_logical_widths","pango_glyph_string_get_width","pango_glyph_string_index_to_x","pango_glyph_string_set_size","pango_glyph_string_x_to_index"]
  ignore_funcs = []
  manual_funcs = []
  name = "GlyphString"

[[types]]
  err_funcs = []
  funcs = ["pango_item_new","pango_item_copy","pango_item_free","pango_item_split"]
  ignore_funcs = []
  manual_funcs = []
  name = "Item"

[[types]]
  err_funcs = ["pango_layout_iter_get_char_extents","pango_layout_iter_get_cluster_extents","pango_layout_iter_get_layout_extents","pango_layout_iter_get_line_extents","pango_layout_iter_get_run_extents","pango_layout_iter_get_run_readonly","pango_layout_iter_next_char","pango_layout_iter_next_cluster","pango_layout_iter_next_line","pango_layout_iter_next_run","pango_layout_iter_get_run"]
  funcs = ["pango_layout_iter_at_last_line","pango_layout_iter_copy","pango_layout_iter_free","pango_layout_iter_get_baseline","pango_layout_iter_get_index","pango_layout_iter_get_layout","pango_layout_iter_get_line","pango_layout_iter_get_line_readonly","pango_layout_iter_get_line_yrange"]
  ignore_funcs = []
  manual_funcs = []
  name = "LayoutIter"

[[types]]
  err_funcs = ["pango_layout_get_cursor_pos","pango_layout_get_extents","pango_layout_get_lines","pango_layout_get_lines_readonly","pango_layout_get_log_attrs","pango_layout_get_log_attrs_readonly","pango_layout_get_pixel_extents","pango_layout_index_to_pos","pango_layout_set_markup_with_accel"]
  funcs = ["pango_layout_new","pango_layout_context_changed","pango_layout_copy","pango_layout_get_alignment","pango_layout_get_attributes","pango_layout_get_auto_dir","pango_layout_get_baseline","pango_layout_get_character_count","pango_layout_get_context","pango_layout_get_ellipsize","pango_layout_get_font_description","pango_layout_get_height","pango_layout_get_indent","pango_layout_get_iter","pango_layout_get_justify","pango_layout_get_line","pango_layout_get_line_count","pango_layout_get_line_readonly","pango_layout_get_pixel_size","pango_layout_get_serial","pango_layout_get_single_paragraph_mode","pango_layout_get_size","pango_layout_get_spacing","pango_layout_get_tabs","pango_layout_get_text","pango_layout_get_unknown_glyphs_count","pango_layout_get_width","pango_layout_get_wrap","pango_layout_index_to_line_x","pango_layout_is_ellipsized","pango_layout_is_wrapped","pango_layout_move_cursor_visually","pango_layout_set_alignment","pango_layout_set_attributes","pango_layout_set_auto_dir","pango_layout_set_ellipsize","pango_layout_set_font_description","pango_layout_set_height","pango_layout_set_indent","pango_layout_set_justify","pango_layout_set_markup","pango_layout_set_single_paragraph_mode","pango_layout_set_spacing","pango_layout_set_tabs","pango_layout_set_text","pango_layout_set_width","pango_layout_set_wrap","pango_layout_xy_to_index"]
  ignore_funcs = []
  manual_funcs = []
  name = "Layout"

[[types]]
  err_funcs = ["pango_context_list_families"]
  funcs = ["pango_context_new","pango_context_changed","pango_context_get_base_dir","pango_context_get_base_gravity","pango_context_get_font_description","pango_context_get_font_map","pango_context_get_gravity","pango_context_get_gravity_hint","pango_context_get_language","pango_context_get_matrix","pango_context_get_metrics","pango_context_get_serial","pango_context_load_font","pango_context_load_fontset","pango_context_set_base_dir","pango_context_set_base_gravity","pango_context_set_font_description","pango_context_set_font_map","pango_context_set_gravity_hint","pango_context_set_language","pango_context_set_matrix"]
  ignore_funcs = []
  manual_funcs = []
  name = "Context"

[[types]]
  err_funcs = ["pango_font_map_list_families"]
  funcs = ["pango_font_map_changed","pango_font_map_create_context","pango_font_map_get_serial","pango_font_map_load_font","pango_font_map_load_fontset"]
  ignore_funcs = ["pango_font_map_get_shape_engine_type"]
  manual_funcs = []
  name = "FontMap"

[[types]]
  err_funcs = ["pango_font_find_shaper","pango_font_get_glyph_extents"]
  funcs = ["pango_font_describe","pango_font_describe_with_absolute_size","pango_font_get_coverage","pango_font_get_font_map","pango_font_get_metrics","pango_font_descriptions_free"]
  ignore_funcs = []
  manual_funcs = []
  name = "Font"

[[types]]
  err_funcs = ["pango_coverage_to_bytes"]
  funcs = ["pango_coverage_copy","pango_coverage_get","pango_coverage_max","pango_coverage_ref","pango_coverage_set","pango_coverage_unref","pango_coverage_from_bytes","pango_coverage_new"]
  ignore_funcs = []
  manual_funcs = []
  name = "Coverage"

[[types]]
  err_funcs = ["pango_fontset_foreach"]
  funcs = ["pango_fontset_get_font","pango_fontset_get_metrics"]
  ignore_funcs = []
  manual_funcs = []
  name = "Fontset"

[[types]]
  err_funcs = ["pango_matrix_transform_distance","pango_matrix_transform_pixel_rectangle","pango_matrix_transform_point","pango_matrix_transform_rectangle"]
  funcs = ["pango_matrix_concat","pango_matrix_copy","pango_matrix_free","pango_matrix_get_font_scale_factor","pango_matrix_get_font_scale_factors","pango_matrix_rotate","pango_matrix_scale","pango_matrix_translate"]
  ignore_funcs = []
  manual_funcs = []
  name = "Matrix"

[[types]]
  err_funcs = ["pango_layout_line_get_extents","pango_layout_line_get_pixel_extents","pango_layout_line_get_x_ranges"]
  funcs = ["pango_layout_line_index_to_x","pango_layout_line_ref","pango_layout_line_unref","pango_layout_line_x_to_index"]
  ignore_funcs = []
  manual_funcs = []
  name = "LayoutLine"

[[types]]
  err_funcs = ["pango_tab_array_new","pango_tab_array_copy","pango_tab_array_free","pango_tab_array_get_positions_in_pixels","pango_tab_array_get_size","pango_tab_array_get_tab","pango_tab_array_get_tabs","pango_tab_array_resize","pango_tab_array_set_tab"]
  funcs = []
  ignore_funcs = ["pango_tab_array_new_with_positions"]
  manual_funcs = []
  name = "TabArray"

[[types]]
  err_funcs = ["pango_font_face_describe","pango_font_face_get_face_name","pango_font_face_is_synthesized","pango_font_face_list_sizes"]
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "FontFace"

[[types]]
  err_funcs = ["pango_font_family_get_name","pango_font_family_is_monospace","pango_font_family_list_faces"]
  funcs = []
  ignore_funcs = []
  manual_funcs = []
  name = "FontFamily"

[[types]]
  err_funcs = []
  funcs = ["pango_renderer_activate","pango_renderer_deactivate","pango_renderer_draw_error_underline","pango_renderer_draw_glyph","pango_renderer_draw_glyph_item","pango_renderer_draw_glyphs","pango_renderer_draw_layout","pango_renderer_draw_layout_line","pango_renderer_draw_rectangle","pango_renderer_draw_trapezoid","pango_renderer_get_alpha","pango_renderer_get_color","pango_renderer_get_layout","pango_renderer_get_layout_line","pango_renderer_get_matrix","pango_renderer_part_changed","pango_renderer_set_alpha","pango_renderer_set_color","pango_renderer_set_matrix"]
  ignore_funcs = []
  manual_funcs = []
  name = "Renderer"
