namespace = "Gio"
version = "2.0"

[[gen_files]]
type = "AppInfo"
funcs = [
	'g_app_info_get_id',
#	'g_app_info_launch',
    'g_app_info_get_supported_types',
]

[[gen_files]]
type = 'DesktopAppInfo'
funcs = [
    'g_desktop_app_info_new_from_filename',
    'g_desktop_app_info_list_actions',
]

[[gen_files]]
type = "Settings"
funcs = [
    'g_settings_new',
	'g_settings_get_value',
	'g_settings_get_string',
	'g_settings_get_boolean',
	'g_settings_get_int',
	'g_settings_get_int64',
	'g_settings_get_uint',
	'g_settings_get_uint64',
	'g_settings_get_double',
	'g_settings_get_enum',
	'g_settings_get_flags',
	'g_settings_get_child',
	'g_settings_get_strv',
	'g_settings_apply',
]

[[gen_files]]
type = "File"
funcs = [
	'g_file_replace',
	'g_file_get_path',
]

[[gen_files]]
type = "Cancellable"

[[gen_files]]
type = 'OutputStream'

[[gen_files]]
type = "FileOutputStream"
funcs = [
	'g_file_output_stream_query_info',
]

[[gen_files]]
type = 'Seekable'

[[gen_files]]
type = "FileInfo"

[[gen_files]]
type = 'Application'
funcs = [
    'g_application_new',
    'g_application_id_is_valid',
    'g_application_set_inactivity_timeout',
    'g_application_hold',
    'g_application_release',
    'g_application_run',
]

[[gen_files]]
type = 'ActionMap'

[[gen_files]]
type = 'ActionGroup'
funcs = [
    'g_action_group_list_actions',
]