funcs = []
namespace = "GObject"
version = "2.0"

[[types]]
  err_funcs = []
  funcs = ["g_value_set_boolean","g_value_set_schar","g_value_set_int64","g_value_set_int","g_value_set_uchar","g_value_set_uint64","g_value_set_uint","g_value_set_float","g_value_set_double","g_value_set_string","g_value_set_instance","g_value_set_pointer","g_value_get_pointer","g_value_get_string","g_value_unset","g_value_copy","g_value_dup_boxed","g_value_dup_object","g_value_dup_param","g_value_dup_string","g_value_dup_variant","g_value_fits_pointer","g_value_get_boolean","g_value_get_boxed","g_value_get_double","g_value_get_enum","g_value_get_flags","g_value_get_float","g_value_get_int","g_value_get_int64","g_value_get_long","g_value_get_object","g_value_get_param","g_value_get_schar","g_value_get_uchar","g_value_get_uint","g_value_get_uint64","g_value_get_ulong","g_value_get_variant","g_value_init_from_instance","g_value_peek_pointer","g_value_reset","g_value_set_boxed","g_value_set_enum","g_value_set_flags","g_value_set_long","g_value_set_object","g_value_set_param","g_value_set_static_boxed","g_value_set_static_string","g_value_set_ulong","g_value_set_variant","g_value_take_boxed","g_value_take_object","g_value_take_param","g_value_take_string","g_value_take_variant","g_value_transform"]
  ignore_funcs = ["g_value_get_char","g_value_set_boxed_take_ownership","g_value_set_char","g_value_set_object_take_ownership","g_value_set_param_take_ownership","g_value_set_string_take_ownership"]
  manual_funcs = ["g_value_get_gtype","g_value_init","g_value_set_gtype","g_value_register_transform_func","g_value_type_compatible","g_value_type_transformable"]
  name = "Value"

[[types]]
  err_funcs = ["g_object_add_toggle_ref","g_object_add_weak_pointer","g_object_bind_property_full","g_object_connect","g_object_disconnect","g_object_dup_data","g_object_dup_qdata","g_object_get","g_object_remove_toggle_ref","g_object_remove_weak_pointer","g_object_replace_data","g_object_replace_qdata","g_object_set_data_full","g_object_set_qdata_full","g_object_weak_ref","g_object_weak_unref"]
  funcs = ["g_object_ref","g_object_unref","g_object_ref_sink","g_object_is_floating","g_object_force_floating","g_object_bind_property","g_object_bind_property_with_closures","g_object_freeze_notify","g_object_get_data","g_object_get_property","g_object_get_qdata","g_object_notify","g_object_notify_by_pspec","g_object_run_dispose","g_object_set_data","g_object_set_property","g_object_set_qdata","g_object_steal_data","g_object_steal_qdata","g_object_thaw_notify","g_object_watch_closure","g_object_interface_find_property","g_object_interface_install_property","g_object_interface_list_properties"]
  ignore_funcs = ["g_object_new","g_object_new_valist","g_object_newv","g_object_get_valist","g_object_set","g_object_set_valist","g_object_compat_control"]
  manual_funcs = []
  name = "Object"

[[types]]
  err_funcs = ["g_closure_add_finalize_notifier","g_closure_add_invalidate_notifier","g_closure_add_marshal_guards","g_closure_invoke","g_closure_remove_finalize_notifier","g_closure_remove_invalidate_notifier","g_closure_set_marshal","g_closure_set_meta_marshal"]
  funcs = ["g_closure_ref","g_closure_sink","g_closure_unref","g_closure_invalidate","g_closure_new_object","g_closure_new_simple"]
  ignore_funcs = []
  manual_funcs = []
  name = "Closure"

[[types]]
  err_funcs = []
  funcs = ["g_binding_get_flags","g_binding_get_source","g_binding_get_source_property","g_binding_get_target","g_binding_get_target_property","g_binding_unbind"]
  ignore_funcs = []
  manual_funcs = []
  name = "Binding"

[[types]]
  err_funcs = ["g_param_spec_set_qdata_full"]
  funcs = ["g_param_spec_get_blurb","g_param_spec_get_default_value","g_param_spec_get_name","g_param_spec_get_name_quark","g_param_spec_get_nick","g_param_spec_get_qdata","g_param_spec_get_redirect_target","g_param_spec_ref","g_param_spec_ref_sink","g_param_spec_set_qdata","g_param_spec_sink","g_param_spec_steal_qdata","g_param_spec_unref"]
  ignore_funcs = []
  manual_funcs = ["g_param_spec_internal"]
  name = "ParamSpec"

[[types]]
  err_funcs = []
  funcs = ["g_type_interface_peek_parent"]
  ignore_funcs = []
  manual_funcs = ["g_type_interface_add_prerequisite","g_type_interface_get_plugin","g_type_interface_peek","g_type_interface_prerequisites"]
  name = "TypeInterface"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = []
  manual_funcs = ["g_type_instance_get_private"]
  name = "TypeInstance"

[[types]]
  err_funcs = []
  funcs = []
  ignore_funcs = ["g_value_array_new","g_value_array_append","g_value_array_copy","g_value_array_free","g_value_array_get_nth","g_value_array_insert","g_value_array_prepend","g_value_array_remove","g_value_array_sort","g_value_array_sort_with_data"]
  manual_funcs = []
  name = "ValueArray"
