namespace = "GObject"
version = "2.0"

[[types]]
name = "Value"
funcs = [
	'g_value_set_boolean',
	'g_value_set_schar',
	'g_value_set_int64',
	'g_value_set_int',
	'g_value_set_uchar',
	'g_value_set_uint64',
	'g_value_set_uint',
	'g_value_set_float',
	'g_value_set_double',
	'g_value_set_string',
	'g_value_set_instance',
	'g_value_set_pointer',
	'g_value_get_pointer',
	'g_value_get_string',
	'g_value_unset',
]

[[types]]
name = "Object"
funcs = [
    'g_object_ref',
    'g_object_unref',
    'g_object_ref_sink',
    'g_object_is_floating',
    'g_object_force_floating',
]

[[types]]
name = "Closure"
funcs = [
    'g_closure_ref',
    'g_closure_sink',
    'g_closure_unref',
    'g_closure_invalidate',
]
