namespace = "GLib"
version = "2.0"

funcs = [
    'g_idle_source_new',
    'g_timeout_source_new',
    'g_timeout_source_new_seconds',
]

[[gen_files]]
type = "Variant"
funcs = [
	'g_variant_unref',
	'g_variant_ref',
	'g_variant_ref_sink',
	'g_variant_get_type',
	'g_variant_is_floating',
    'g_variant_new_boolean',
    'g_variant_get_strv',
    #'g_variant_get_string', // manual
]

[[gen_files]]
type = "VariantType"
funcs = [
]

[[gen_files]]
type = "Error"
funcs = [
    'g_error_free',
]

[[gen_files]]
type = "MainLoop"
funcs = [
    'g_main_loop_ref',
    'g_main_loop_unref',
    'g_main_loop_run',
    'g_main_loop_quit',
    'g_main_loop_get_context',
	'g_main_loop_is_running',
	'g_main_loop_new',
]

[[gen_files]]
type = "MainContext"
funcs = [
    'g_main_context_ref',
    'g_main_context_unref',
    'g_main_context_default',
    'g_main_context_new',
    'g_main_context_iteration',
    'g_main_context_find_source_by_id',
	'g_main_context_pending',
]

[[gen_files]]
type = "Source"
funcs = [
    'g_idle_source_new',
    'g_timeout_source_new',
    'g_timeout_source_new_seconds',
    'g_source_ref',
    'g_source_unref',
    'g_source_set_closure',
    'g_source_attach',
    'g_source_destroy',
    'g_source_is_destroyed',
    'g_source_set_priority',
    'g_source_get_priority',
    'g_source_set_can_recurse',
    'g_source_get_can_recurse',
    'g_source_get_id',
    'g_source_get_name',
    'g_source_set_name',
    'g_source_set_name_by_id',
    'g_source_get_context',
    'g_source_get_time',
    'g_source_remove',
]

